### PR TITLE
Replaced localStorage with chrome Storage API

### PR DESCRIPTION
**Pull request by piperun**
It should work right out of the box, but only done certain tests and been used a bit in production.

Also if Google sync isn't available it'll default to storage.local.

The only thing that might be a big sketchy is the localStorage to chrome storage converter.

### CODE REVIEW

**Comment by bogenpirat** [comment]
hey there, been a while. let me know if this is no longer of interest to you.

i appreciate the boatload of work you guys put into this, especially considering you're clearly better-versed with js development than i am.

however, i'm a bit torn on this one. the functionality has been pitched before, however for my specific use case, i actually **wouldn't** want to sync my settings across my google account. this is owed to the fact that depending on which computer i'm using, the torrent clients i'm addressing are typically different ones. furthermore, there's that bit on the docs about storage being unencrypted, and i personally don't want the credentials to my torrent clients synced to every machine that i use chrome on.

i realize that i likely represent a minority with this one, but i'm still uneasy about these factors. in addition, this PR includes a bunch of unrelated style "fixes" that i don't agree with, so i'm shelving this one. sorry.

**Comment by piperun** [comment]
Hi there!
Just here to clarify that `chrome.storage.sync() `automatically defaults to `chrome.storage.local()` and it's why I added it in the first place to allow people the option.

And afaik the old solution is not much better in terms of security but I could be wrong.

But I understand the other fixes, but those are there from what I can remember to make storage work.

**Comment by bogenpirat** [comment]
>Just here to clarify that chrome.storage.sync() automatically defaults to chrome.storage.local() and it's why I added it in the first place to allow people the option.

from what i recall, what this actually means is that it'll use `storage.local` if `storage.sync` is not available, no? that way, allowing users to "choose" then is only true in the sense that they can disable extension syncing. or am i completely off?

>And afaik the old solution is not much better in terms of security but I could be wrong.

that is true, localStorage isn't encrypted or anything locally either. but keeping encrypted data locally and sending it elsewhere are separate issues. i'm not gonna pretend to be an evangelist when it comes to security, but in practical terms, i dislike the notion of just syncing these credentials everywhere.

**Comment by piperun** [comment]
> from what i recall, what this actually means is that it'll use storage.local if storage.sync is not available, no? that way, allowing users to "choose" then is only true in the sense that they can disable extension syncing. or am i completely off?
I may have misspoken in the sense of "choice".
It'll use `storage.local` if you have not setup a Google Account and has logged into Chrome or for some reason can't sync the data.
And I figured it's cleaner and makes sense that if an user has logged into Chrome that they wish to utilize it's sync functionality (since syncing is more less done automatically afaik with no option to disable it, so the act of logging in is the "choice").

But you can easily change all the `sync` to `local` if you so wish, there should be 0 issues with it, since data wise they behave and expect the exact same.

**Pull request closed without merging**
