### PR TITLE
Adds optional sound-on-notification, to start addressing #217

### PR DESCRIPTION
**Pull request by JPRuskin**

### CODE REVIEW

**Comment by JPRuskin** [comment]
@bogenpirat : Is there any chance of this being merged as is, or would you prefer a more complete solution with customisable sounds?

**Comment by bogenpirat** [comment]
the code changes look good. do you have any info on licensing of the audio files you've included? if these are to become standard for RTA, that means they might become part of the RTA brand (for lack of a better term) and i'd hate to be the recipient of some angry copyright notice some day.

ideally, i'd want to let users choose their notification sounds, but have a default set of sounds as a backup. i can do that change myself when i find the time, and when i do, it likely won't take much longer than the release itself.

if you happen to have an idea about making customization work quickly and really want to invest your time, go ahead. if not, just let me know and i'll merge this for now with a release date pending.

PS: sorry for the long radio silence, i'm having a bit of a hard time finding the time these days. i'll make an effort to get to ticking off a few boxes in the coming weeks.

**Comment by JPRuskin** [comment]
The sounds are taken from this:
https://opengameart.org/content/menu-selection-click
I shifted the pitch of one of them to change the tone between Success and Failure.

It's licensed with [CC By 3.0](https://creativecommons.org/licenses/by/3.0/). It asks for attribution, and I have included the artist name (as listed on the site) and the URL from which I pulled it within the .ogg metadata (under the Artist and Comments field). I thought that was enough - but having said that, I apparently did not read well enough - I should also have included a link to the license and indicated that I changed one of them.

If you think it's sufficient, I'll push new versions with that additional data. If not, I can try and find some more easily licensed files. I found it surprisingly hard to find a sound that worked for me - if you have any preference for the defaults... let me know? (or give an example)

I had some thoughts about adding the customization, but have sort of lost track of where I was (was waiting to see how easily stuff got accepted / not before I spent much time). 

Thanks for the response - no worries on the silence, I was just curious if it was acceptable or not. Long time user of the plugin, thanks for all your hard work! Hoping to contribute a little more in the future, if that suits you.

**Comment by bogenpirat** [comment]
yeah, i know, it's been a while. sorry about that. still interested in this? i fixed a couple of things from the PR, would you mind giving the code from 476fe4bedd36b126c463aef10eab3f5de6b710a3 a quick test?

**Comment by JPRuskin** [comment]
No worries, I've been quite busy too. I'll see if I can remember what's what. Thanks for the accept / merge.

**Comment by adamwinn** [comment]
@bogenpirat  This says it's merged but I'm not getting any sounds. I'm on 1.2.15. Does another release need to be made?

**Pull request merged**
